name: Test Secret Token

on:
  workflow_dispatch:  # Menjalankan workflow secara manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret Token
        run: |
          echo "Testing access to USER_TOKEN"
          if [ -z "${{ secrets.USER_TOKEN }}" ]; then
            echo "Secret not found!"
          else
            echo "Secret is accessible! ${{ secrets.USER_TOKEN }}"
            # Uncomment the next line to display the token for testing purposes ONLY!
            # echo "User Token: ${{ secrets.USER_TOKEN }}"
          fi
