name: Update README

on:
  workflow_dispatch:   # Menjalankan workflow secara manual
  schedule:
    - cron: '0 */12 * * *'   # Menjalankan workflow setiap 12 jam
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: amaralfatah/profile-readme-stats@master   # Menggunakan fork dari akun Anda
        with:
          token: ${{ secrets.USER_TOKEN }}

      - name: Update README.md
        run: |
          git config user.name "Amar Al Fatah"
          git config user.email "amaralfatah.main@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.USER_TOKEN }}@github.com/amaralfatah/amaralfatah.git
          git add .
          git commit -m "Update README"
          git push https://x-access-token:${{ secrets.USER_TOKEN }}@github.com/amaralfatah/amaralfatah.git HEAD:main
