name: Update README

on:
  workflow_dispatch:   # Menjalankan workflow secara manual
  schedule:
    - cron: '0 */12 * * *'   # Menjalankan workflow setiap 12 jam
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate README.md
        uses: amaralfatah/profile-readme-stats@master   # Menggunakan fork dari akun Anda
        with:
          token: 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

      - name: Update README.md
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token: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@github.com/amaralfatah/amaralfatah.git
          git add .
          git commit -m "Update README"
          git push https://x-access-token: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@github.com/amaralfatah/amaralfatah.git HEAD:main
